<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check contract currency</name>
  <uuid>650d6be3-62f0-4837-ab26-6e9871bd895c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
    set contract to a Contract in the contracts ;
    
if  the currency of contract is null
 then 
    add "Error: a currency must be set on the contract " + the name of contract to decision;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
