<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>advice rule</name>
  <uuid>f2f86b56-68f8-4666-9993-d58436476d71</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then
	set decision to "Hello" + Name + "!";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
