<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ffb922e7-3ae3-4034-b2cf-2dfab7af5f32</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry don't have enough info. " ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
